"""Update recurring transaction fields

Revision ID: 98da502f60b1
Revises: 584afbe48d88
Create Date: 2025-01-11 16:29:32.034521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98da502f60b1'
down_revision = '584afbe48d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_occurrence', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recurring_transaction', schema=None) as batch_op:
        batch_op.drop_column('next_occurrence')

    # ### end Alembic commands ###
